### ISSUE TITLE
Integration with zipline

### ISSUE THREAD

**Issue by florentchandelier** [ranaroussi/qtpylib#1]
Hi, 
excellent share for the community.
Have you thought of integrating with Zipline - https://github.com/quantopian/zipline
Can you provide some insights as per where you would start, I would gladly try to bridge them in order to get a backup in case Quantopian (commercial zipline for live trading) goes down.

**Comment by ranaroussi** [comment]
Hey,

Making QTPyLib work with Zipline strategies shouldn't be extremely hard theoretically.

That being said, although I've played with Zipline a bit, I can't say that I'm fluent with it and therefore won't be able think of everything that might get broken and will probably never get a 100% coverage (and even less as both libraries mature).

Also, I still push updates to QTPyLib every single day and I feel it needs to first get past a beta version before I pursue this... :)

For now, I think the best approach would be to create a guide on how to convert a strategy to work with QTPyLib. Since both libraries are event based and using Numpy/Pandas, it should be pretty strait forward.

In my example, I tried to use a very similar strategies to the one used by Zipline in order to emphasis the differences and similarities of a basic strategy.

- http://www.zipline.io/index.html#quickstart
- http://qtpylib.io/docs/latest/#write-your-algorithm

Let me know what you think... Does this make sense? :)

Ran
