### ISSUE TITLE
[V2 Feature Request] Adding Choppiness Index

### ISSUE THREAD

**Issue by Dante2333** [ranaroussi/qtpylib#119]
Chop index description:
https://www.tradingview.com/wiki/Choppiness_Index_(CHOP)
Python implementation:
https://qiita.com/hoshitter1/items/d241cd2d13b72df9a204

**Comment by ranaroussi** [comment]
Will do!

In the meantime, you can use this in your code:

```python
import qtpylib.indicators as ti

def chopiness(bars, lookback=14):
    atrsum = ti.true_range(bars).rolling(lookback).sum()
    highs = bars['high'].rolling(lookback).max()
    lows = bars['low'].rolling(lookback).min()
    return 100 * np.log10(atrsum / (highs - lows)) / np.log10(n)

# use:
bars['chopiness'] = chopiness(bars, 14)
```

**Comment by Dante2333** [comment]
Thank you so much.

**Comment by Dante2333** [comment]
@ranaroussi shouldnt it be choppiness rather than chopiness?

**Comment by ranaroussi** [comment]
Whoops :)




On 2 Jun 2019, at 16:00, Dante <notifications@github.com> wrote:

@ranaroussi <https://github.com/ranaroussi> shouldnt it be choppiness
rather than chopiness?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ranaroussi/qtpylib/issues/119?email_source=notifications&email_token=AAJBNMVHXR5KPBP43QVU7JLPYO76TA5CNFSM4HRRNGKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWXVDEA#issuecomment-498028944>,
or mute the thread
