### ISSUE TITLE
Dashboard cannot find blotter

### ISSUE THREAD

**Issue by rastegarr** [ranaroussi/qtpylib#33]
I have looked at many different libraries and among all the options out there I really like the simplicity and power of QtPyLib. Thanks for sharing it!

I installed the module and prepared all the pre-requisites. I tried to run the example that comes with documentation. I successfully run blotter.py. However, when I run the dashboard.py, I get this message, even though the blotter is running:

python dashboard.py 
[ERROR] Cannot connect to running Blotter [MainBlotter]

What could be the reason?

**Comment by ranaroussi** [comment]
Thanks for checking out QTPyLib!

Is the blotter running on a separate process while trying to run the dashboard?

**Comment by rastegarr** [comment]
I tried it in two different ways: 
1) ran the blotter on a terminal and the dashboard on another terminal.  

2) I ran both on one terminal; 

python blotter.py
Ctl+Z 
fg
python dashboard.py

Both had same issue.

**Comment by ranaroussi** [comment]
Congratulations! You found a bug :)

I've fixed the bug and added a few more code improvements... Upgrade to the latest version (1.5.38) using:

```
$ pip install qtpylib --upgrade --no-cache-dir
```

...and let me know if the problem was resolved.

**Comment by rastegar527** [comment]
The problem is not fixed. Now I get a message indicating the IP address is in use by another service even though I haven't really done anything different.

**Comment by ranaroussi** [comment]
Can you post the exact message you're getting (including the logger prefix)?

By the looks of if, is seems that you have another dashboard running. If this is the case, it's probably because it wasn't terminated properly. Try issuing `killall python` and re-run the blotter and dashboard to see if this was resolved.

If you actually have a different service using that ip/port, try changing it to `127.0.0.1` (or your local ip) in your dashboard.py:

```
if __name__ == "__main__":
    dashboard = Dashboard(host = "127.0.0.1")
    dashboard.run()
```

**Comment by rastegar527** [comment]
It works now. Thanks a lot for all the help Ran!
