### ISSUE TITLE
Could not get  FUT data.

### ISSUE THREAD

**Issue by homeyi** [ranaroussi/qtpylib#7]
Ran,
Thank for you QTPyLib,I have tested severa weeks,It is very execllent!!! 

I have a problem about FUT can not get quote and tick,

Because i use my live account to try get XINA50 FUT(i have subscribed data) quote and tick ,

Like this:(instruments = [("XINA50", "FUT", "SGX", "USD", 201610, 0.0, "")],) But can not get it. 

I do not know how to right do it,Can you give me some advice,

Thanks and kind regards,

**Comment by ranaroussi** [comment]
Hi,

I'm not familiar with this contract, but it appears that you're doing everything right... 

I tried getting contract specifications using Python and got it - which means the Tupple is correct.

However since I'm not subscribed to SGX, all I get are zeros for bid/ask/last. When I use a fake contract I don't even get that - so this also indicates to me that the tupple is correct.

Can see charts for this instrument directly on TWS?

**Comment by gitsamsit** [comment]
Hi Ran
I have tried with ES, but I am not getting any data as well.

But checked with STK and CASH, which works fine.
'-------------------------------------------------------------------------------------------
My FUT test tuple is ("ES", "FUT", "GLOBEX", "USD", 201611, 0.0,"")
and I can see entry in symbols.csv as: 
symbol,sec_type,exchange,currency,expiry,strike,opt_type
ES,FUT,GLOBEX,USD,201611.0,0.0,
'-------------------------------------------------------------------------------------------
when I check the log msg, tws returns error code 200, which is "No security definition has been found for the request".

I am not sure, but is it to do with expiry field (201611.0 instead of 201611)

Thanks and kind Regards Sam

**Comment by homeyi** [comment]
Hi gitsamsit , 
ES must be subscribed by TWS,edemo/demouser can not get ES data.

**Comment by ranaroussi** [comment]
ES does not have November expiration. Please try using 

`("ES", "FUT", "GLOBEX", "USD", 201612, 0.0,"")`

**Comment by gitsamsit** [comment]
Hi Ran, homeyi

Thanks for the response, tried with 201612 still getting the same msg. @homeyi I am using sim account for test not edemo, I guess it should work with sim account.

**Comment by gitsamsit** [comment]
log msg:
{"TimeStamp": "20161018 12:27:08 PM", "level": "INFO", "msg": "Connection established..."},
{"TimeStamp": "20161018 12:27:14 PM", "level": "INFO", "msg": "Contract Added [ESZ2016]"},
{"TimeStamp": "20161018 12:27:14 PM", "level": "INFO", "msg": "ibCallBack caller handleError, msg 200, kwargs {}"},

**Comment by ranaroussi** [comment]
I'm not sure how 201611.0 was added to your symbols.csv. Can you remove this line and restart blotter.py?

**Comment by gitsamsit** [comment]
Hi Ran
removed .csv and restarted blotter.
now symbols.csv looks as
symbol,sec_type,exchange,currency,expiry,strike,opt_type
ES,FUT,GLOBEX,USD,201612.0,0.0,
and still getting same msg.

**Comment by ranaroussi** [comment]
Please post your complete code so I can run it locally and figure out
what's happening.

Thanks!

**Comment by gitsamsit** [comment]
sure I will post it in few mints. meanwhile FYI I tried placing ES order using ezibpy, which works nice.

**Comment by gitsamsit** [comment]
Here is blotter and strategy code. Please letme know should I send the complete folder.

Thanks

blotter.py
```
#!/usr/bin/env python
import logging
logging.basicConfig(filename='log-ex-bl.json', level=logging.DEBUG,
    format='{"TimeStamp": "%(asctime)s", "level": "%(levelname)s", "msg": "%(message)s"},', datefmt='%Y%m%d %I:%M:%S %p')

from qtpylib.blotter import Blotter

class MainBlotter(Blotter):
    pass # we just need the name

# ===========================================
if __name__ == "__main__":
    blotter = MainBlotter( )
    blotter.run()

```

strategy.py
```
from qtpylib.algo import Algo

class StrBasicES(Algo):
    def on_bar(self, instrument):
        if instrument.positions['position'] == 0:
            instrument.buy(1)
        else:
            instrument.exit()

if __name__ == "__main__":
    strategy = StrBasicES(
        instruments = [ ("ES", "FUT", "GLOBEX", "USD", 201612, 0.0,"") ],
        resolution  = "1T"
    )
    strategy.run()

```

**Comment by ranaroussi** [comment]
Works great here!

I did notice the `201612.0` but it works just as well.. I did pushed version 1.4.91 that forces the expiry to be saved as int instead of float but that shouldn't prevent it from working in any case.

As for the 200 error. I see it once on every established connection - no matter which library I use (also when using IbPy only) - so I guess this is something we can feel comfortable ignoring :)

**Comment by homeyi** [comment]
Ran,
i can see charts for this instrument.
i found not some problem,i  do not know how can i check it.

`the contract info like this:
'''
FTSE/Xinhua China A50
Security Type  FUT
Underlying  XINA50 IND
Contract Month OCT16
Expiration Date OCT 28 '16
Last Trading Date OCT 28 '16 16:35 HKT
Currency USD
Multiplier 1
Exchange SGX
Trading Class CN
Symbol CNV16
Product Type Equity Index
Settlement Method Cash
Trading Hours: October 18, 2016  Calendar 
Total Available Hours
17:15 HKT - 02:00 HKT (17:15 CST - 02:00 CST)
09:00 HKT - 16:35 HKT (09:00 CST - 16:35 CST)
Current Margin Requirements
Intraday Initial
 1446.25
Intraday Maintenance
  1157.00
Overnight Initial
  1446.25
Overnight Maintenance
1157.00
'''
`

**Comment by gitsamsit** [comment]
Ran

It works great here too! 

Got new version 1.4.91 , and tested yep now its int instead of float.

Thanks for the help :)

**Comment by gitsamsit** [comment]
@homeyi try using new version it may work

**Comment by homeyi** [comment]
@gitsamsit  ok i try again

**Comment by homeyi** [comment]
have update new version,but my here still not get XINA50 FUT data, i try new define instruments but ...

```
from qtpylib.algo import Algo
from qtpylib import futures

class DumbAlgo(Algo):

    def on_start(self):
        print("start")
        pass

    def on_fill(self, instrument, order):
        print("fill")
        pass

    def on_quote(self, instrument):
        # print(instrument)

        # print("quote")
        pass

    def on_tick(self, instrument):
        print("tick"+instrument)
        # print(instrument)
        pass

    def on_bar(self, instrument):
        bars = instrument.get_bars()
        print("\n\n--- BAR ---"+instrument)
        print(bars['close'])

        # buy if position = 0, sell if in position > 0
        if instrument.positions['position'] == 0:
            print(">> BUY"+instrument)
            # instrument.buy(100)
        else:
            print(">> EXIT (SELL)"+instrument)
            # instrument.exit()

        print("\n\n")

if __name__ == "__main__":
    # initialize the algo
    strategy = DumbAlgo(
        instruments = [
            futures.make_tuple("XINA50", 201610, exchange="SGX"),
            futures.make_tuple("XINA50", 201611),
            ("XINA50", "FUT", "SGX", "USD", 201612),
           ],
        resolution  = "1T",
        tick_window = 10,
        bar_window  = 10
    )

    # run the algo
    strategy.run()
```

**Comment by homeyi** [comment]
by the way:
i try define instruments as like this:
```
        instruments = [
            futures.make_tuple("XINA50", 201610, exchange="SGX"),
            futures.make_tuple("XINA50", 201611),
            ("XINA50", "FUT", "SGX", "USD", 201612),
           ],
```
only first define can works. `futures.make_tuple("XINA50", 201610, exchange="SGX"),`

**Comment by ranaroussi** [comment]
Glad to hear it! 

Marking this as closed :)
