### ISSUE TITLE
Issue with SQL syntax when executed programmatically

### ISSUE THREAD

**Issue by gargleblaster** [ranaroussi/qtpylib#75]
I'm just getting started with QtPyLib, so I've got a trivially simply test program:

```
from qtpylib.blotter import Blotter

class TestBlotter(Blotter):
    pass

if __name__ == "__main__":
    blotter = TestBlotter(
        dbhost="localhost",
        dbname="qtpy",
        dbuser="qtpy",
        dbpass="qtpy",
        ibport=4001,
        orderbook=True
    )

    blotter.run()

```
I installed a new copy of MySQL for this purpose:
Server version: 5.7.20-log MySQL Community Server (GPL)

When I run this program, I get this error:

``` bash:
> C:\sw\qtpylib-master\venv\Scripts\python.exe C:/sw/qtpylib-master/qtpylib/TestBlotter.py
> Traceback (most recent call last):
>   File "C:/sw/qtpylib-master/qtpylib/TestBlotter.py", line 16, in <module>
>     blotter.run()
>   File "C:\sw\qtpylib-master\qtpylib\blotter.py", line 709, in run
>     self.mysql_connect()
>   File "C:\sw\qtpylib-master\qtpylib\blotter.py", line 1167, in mysql_connect
>     self.dbcurr.execute(open(path['library'] + '/schema.sql', "rb").read())
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\cursors.py", line 165, in execute
>     result = self._query(query)
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
>     conn.query(q)
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\connections.py", line 860, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
>     result.read()
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\connections.py", line 1349, in read
>     first_packet = self.connection._read_packet()
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
>     packet.check_error()
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\connections.py", line 384, in check_error
>     err.raise_mysql_exception(self._data)
>   File "C:\sw\qtpylib-master\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
>     raise errorclass(errno, errval)
> **pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `_version_` (\n  `id` int(11) unsigned NOT NULL AUTO_I' at line 21")**
> 2017-12-24 18:08:21,000 [INFO] qtpylib.blotter: Blotter stopped...
> 2017-12-24 18:08:21,000 [INFO] qtpylib.blotter: Deleting runtime args...
> 2017-12-24 18:08:21,000 [INFO] qtpylib.blotter: Disconnecting from MySQL...
> 
> Process finished with exit code 0
> 
```
However, I opened schema.sql in Intellij and ran the "offending" CREATE TABLE command, and it worked fine:

``` bash:
> [2017-12-24 18:08:08] Connected
> sql> CREATE TABLE IF NOT EXISTS `_version_` (
>   `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
>   `version` varchar(8) DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
> [2017-12-24 18:08:09] completed in 203ms
> 
```
Any idea what might be going wrong when running the Python code?

**Comment by liambarstad** [comment]
My solution involves ditching the built in database altogether and hand-rolling it myself. It's not really a solution if your app revolves around the built in mysql database, but the sql script that initializes the database is found (on your machine) under "C:\sw\qtpylib-master\qtpylib\schema.sql" if you want to recreate it.
in order to make it forget the database, you need to pass in "dbskip=True" when you initialize TestBlotter.

next, in the file "C:\sw\qtpylib-master\qtpylib\blotter.py" on line 1145, under the definition for  mysql.connect(), I added the lines:

if self.args['dbskip']:
    return

this practice is used on all the other methods in this class to skip the database if the argument is passed in except for this one (to my knowledge)

**Comment by ranaroussi** [comment]
@gargleblaster - try executing the sql file directly in mysql and then run blotter. Hopefully this will work

**Comment by solidgains** [comment]
I ran the schema.sql file and it worked. Btw, I very much appreciate this solution for IB. It's cross platform and fairly concise, coming from a Java background I'm enjoying this push into Python. Thank you. I plan to use it for implementing simple futures automated trading strategies.

**Comment by etsygankov** [comment]
Recently I've run into the same kind of issue. In my case, it was caused by the fact that the method `cursor.execute()` of `pymysql` library can't  execute several SQL statements separated by a semicolon at once. To solve the problem it is sufficient to specify `client_flag=MULTI_STATEMENTS` inside of the call to `pymysql.connect` and to add an import statement `from pymysql.constants.CLIENT import MULTI_STATEMENTS` at the beginning of the `qtpylib/blotter.py`.

**Comment by ranaroussi** [comment]
Thanks @etsygankov - adding this to my next push!

At first, I wasn't able to reproduce this since I got the same flag number when testing  on my machine - with or without adding ``client_flag=MULTI_STATEMENTS``. However, on a virtual machine with a new anaconda install it worked only with that flag, so I guess this is somehow machine/install dependent and should be explicitly stated. Good to know 😄

**Comment by etsygankov** [comment]
It is great that such a solution for IB exists, I was really excited to find it. Thank you @ranaroussi for developing and keeping it up!😄

**Comment by llevar** [comment]
It would be good to get this into master, or at least add a note to the documentation about this issue while it still exists.
